version: "3.8"

services:
  app:
    image: my-express-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: node app.js
    restart: unless-stopped
